### 请求 demo04-student/create 接口 => 成功
POST {{baseUrl}}/infra/demo04-student/create
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

### 请求 demo04-student/list 接口 => 成功
GET {{baseUrl}}/infra/demo04-student/list
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

### 请求 demo04-student/get 接口 => 成功
GET {{baseUrl}}/infra/demo04-student/get?id=3
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

### 请求 demo04-student/page 接口 => 成功
GET {{baseUrl}}/infra/demo04-student/page
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}