drop table if exists `user_info`;
create table if not exists `user_info`
(
    "id"     bigint(20)  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"   VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    "email"  VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    "mobile" VARCHAR(50) NULL DEFAULT NULL COMMENT '手机号',
    PRIMARY KEY ("id")
);