CREATE TABLE IF NOT EXISTS "qg_sys_shop" (
                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "shop_name" varchar NOT NULL,
                                             "shop_city" varchar NOT NULL,
                                             "shop_address" varchar NOT NULL,
                                             "shop_address_num" varchar NOT NULL,
                                             "shop_group" varchar,
                                             "status" int NOT NULL,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             "tenant_id" bigint NOT NULL,
                                             PRIMARY KEY ("id")
    ) COMMENT '店面';