DROP TABLE IF EXISTS `haoka_on_sale_product`;
CREATE TABLE `haoka_on_sale_product`
(
    `id`                            bigint(20) NOT NULL PRIMARY KEY COMMENT 'ID',
    `parent_product_id`             bigint(20) NOT NULL COMMENT '产品',
    `name`                          varchar(512) NOT NULL COMMENT '商品名称',
    `sku`                           varchar(512) NOT NULL COMMENT '商家编码',
    `precautions`                   varchar(1024) COMMENT '商品注意点',
    `selling_points`                varchar(1024) COMMENT '卖点，使用逗号隔开',
    `acceptance_rules`              varchar(512) COMMENT '承接佣金规则',
    `settlement_requirement`        varchar(512) COMMENT '结算要求',
    `settlement_rules_inner`        varchar(512) COMMENT '佣金结算规则（内部）',
    `need_sale_upload_image`        bit(1)       NOT NULL DEFAULT b'0' COMMENT '销售页上传照片',
    `main_img`                      varchar(2048) COMMENT '产品主图',
    `share_img`                     varchar(2048) COMMENT '商品分享图',
    `detail`                        longtext COMMENT '商品详情',
    `other_note`                    longtext COMMENT '其他备注',
    `monthly_rent`                  varchar(512) COMMENT '月租',
    `voice_call`                    varchar(512) COMMENT '语言通话',
    `universal_traffic`             varchar(512) COMMENT '通用流量',
    `targeted_traffic`              varchar(512) COMMENT '定向流量',
    `belong_area`                   text COMMENT '归属地',
    `package_details`               longtext COMMENT '套餐详情',
    `package_discount_period`       int(11) COMMENT '套餐优惠期',
    `package_discount_period_start` int(11) COMMENT '优惠期起始时间:当月，次月，三月',
    `on_sale`                       bit(1)       NOT NULL DEFAULT b'1' COMMENT '上架',
    `is_top`                        bit(1)                DEFAULT b'0' COMMENT '是否顶置',
    `dept_id`                       bigint(20) COMMENT '部门ID',
    `creator`                       varchar(64)  NOT NULL DEFAULT '' COMMENT '创建者',
    `create_time`                   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`                       varchar(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    `update_time`                   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`                       bit(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id`                     bigint(20) NOT NULL DEFAULT 0 COMMENT '租户编号',
    UNIQUE (tenant_id, sku)
) COMMENT = '在售产品';
